name: kidde-collector
services:
  kidde-collector:
    container_name: kidde-collector
    environment:
      SEND_TO_MQTT: "Y"
      SEND_TO_INFLUXDB: "N"
      KIDDLE_MQTT_HOST: X.X.X.X
      KIDDLE_MQTT_USERNAME: xx
      KIDDLE_MQTT_PASSWORD: xxx
      KIDDE_COLLECTOR_KIDDE_PASSWORD: xxx
      KIDDE_COLLECTOR_KIDDE_USERNAME: xxx@xxx.xxx
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "test -f health/last_successful_cycle && [ $(($(date +%s) - $(stat -c %Y health/last_successful_cycle))) -lt 240 ]"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: always